id: I3E9B4B32
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T15:23:10+00:00'
last_modified: '2022-06-07T12:38:41.368292+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS20242
  title: ས་སྐྱ་ལེགས་བཤད་བོད་རྒྱ་དབྱིན་གསུམ་ཤན་སྦྱར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    A907:
      image_group_id: I8LS20244
      title: ''
      total_pages: 253
      order: 1
      base_file: A907.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
