id: P000679
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W8LS20242
  title: ས་སྐྱ་ལེགས་བཤད་བོད་རྒྱ་དབྱིན་གསུམ་ཤན་སྦྱར།
  author: ''
  volumes:
    c58aad30650347c094a549900b99cf80:
      image_group_id: I8LS20244
      title: ''
      volume_number: 1
      total_pages: 253
